server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///accumulation?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: abc
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.jt: debug
